/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cramer2x2;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.applet.AudioClip;
import javax.swing.ImageIcon;
/**
 *
 * @author humer
 */

public class NewJFrame extends javax.swing.JFrame  {
    int xMouse,yMouse;
    private boolean is4x4=false;
    private boolean is3x3=false;
    private boolean is2x2=false;
    MetodoCramer m1 = new MetodoCramer();
    public NewJFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/newpackage/matriz.png")).getImage());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background = new javax.swing.JPanel();
        valor03 = new javax.swing.JTextField();
        valor00 = new javax.swing.JTextField();
        valor01 = new javax.swing.JTextField();
        valor02 = new javax.swing.JTextField();
        valor10 = new javax.swing.JTextField();
        valor11 = new javax.swing.JTextField();
        valor13 = new javax.swing.JTextField();
        valor20 = new javax.swing.JTextField();
        valor21 = new javax.swing.JTextField();
        valor23 = new javax.swing.JTextField();
        valor12 = new javax.swing.JTextField();
        valor22 = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        A = new javax.swing.JPanel();
        separador3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        separador1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador6 = new javax.swing.JSeparator();
        separador5 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        salir1 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        B = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        valor04 = new javax.swing.JTextField();
        valor14 = new javax.swing.JTextField();
        valor24 = new javax.swing.JTextField();
        separador7 = new javax.swing.JSeparator();
        separador8 = new javax.swing.JSeparator();
        separador9 = new javax.swing.JSeparator();
        valor30 = new javax.swing.JTextField();
        valor31 = new javax.swing.JTextField();
        valor33 = new javax.swing.JTextField();
        valor32 = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        separador10 = new javax.swing.JSeparator();
        separador11 = new javax.swing.JSeparator();
        separador12 = new javax.swing.JSeparator();
        separador13 = new javax.swing.JSeparator();
        valor34 = new javax.swing.JTextField();
        separador14 = new javax.swing.JSeparator();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boton4 = new javax.swing.JPanel();
        MAX = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        separador15 = new javax.swing.JSeparator();
        MIN = new javax.swing.JTextField();
        separador16 = new javax.swing.JSeparator();
        label16 = new javax.swing.JLabel();
        llenar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        respuestas = new javax.swing.JTextArea();

        jLabel12.setText("jLabel12");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valor03.setForeground(java.awt.Color.gray);
        valor03.setText("0");
        valor03.setBorder(null);
        valor03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor03MousePressed(evt);
            }
        });
        background.add(valor03, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, 20));

        valor00.setBackground(new java.awt.Color(255, 255, 255));
        valor00.setForeground(java.awt.Color.gray);
        valor00.setText("0");
        valor00.setBorder(null);
        valor00.setSelectedTextColor(new java.awt.Color(51, 51, 255));
        valor00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor00MousePressed(evt);
            }
        });
        background.add(valor00, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 40, 20));

        valor01.setForeground(java.awt.Color.gray);
        valor01.setText("0");
        valor01.setBorder(null);
        valor01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor01MousePressed(evt);
            }
        });
        background.add(valor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 40, 20));

        valor02.setForeground(java.awt.Color.gray);
        valor02.setText("0");
        valor02.setBorder(null);
        valor02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor02MousePressed(evt);
            }
        });
        background.add(valor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 40, 20));

        valor10.setForeground(java.awt.Color.gray);
        valor10.setText("0");
        valor10.setBorder(null);
        valor10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor10MousePressed(evt);
            }
        });
        background.add(valor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 40, 20));

        valor11.setForeground(java.awt.Color.gray);
        valor11.setText("0");
        valor11.setBorder(null);
        valor11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor11MousePressed(evt);
            }
        });
        background.add(valor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 40, 20));

        valor13.setForeground(java.awt.Color.gray);
        valor13.setText("0");
        valor13.setBorder(null);
        valor13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor13MousePressed(evt);
            }
        });
        background.add(valor13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 40, 20));

        valor20.setForeground(java.awt.Color.gray);
        valor20.setText("0");
        valor20.setBorder(null);
        valor20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor20MousePressed(evt);
            }
        });
        background.add(valor20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, 20));

        valor21.setForeground(java.awt.Color.gray);
        valor21.setText("0");
        valor21.setBorder(null);
        valor21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor21MousePressed(evt);
            }
        });
        background.add(valor21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 40, 20));

        valor23.setForeground(java.awt.Color.gray);
        valor23.setText("0");
        valor23.setBorder(null);
        valor23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor23MousePressed(evt);
            }
        });
        background.add(valor23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 40, 20));

        valor12.setForeground(java.awt.Color.gray);
        valor12.setText("0");
        valor12.setBorder(null);
        valor12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor12MousePressed(evt);
            }
        });
        background.add(valor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 40, 20));

        valor22.setForeground(java.awt.Color.gray);
        valor22.setText("0");
        valor22.setBorder(null);
        valor22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor22MousePressed(evt);
            }
        });
        background.add(valor22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 40, 20));

        label6.setText("x3 +");
        background.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel2.setText("x1 +");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel3.setText("x1 +");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        label7.setText("x1 +");
        background.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        label3.setText("x2 +");
        background.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        label2.setText("x2 +");
        background.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        label1.setText("x2 +");
        background.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        label4.setText("x3  +");
        background.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        label5.setText("x3 +");
        background.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        A.setBackground(java.awt.Color.gray);
        A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 20, 20));
        background.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 40, 10));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, 10));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, 10));
        background.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 40, 10));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, 10));
        background.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 40, 10));
        background.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 40, 10));
        background.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 40, 10));
        background.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 40, 10));
        background.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 40, 10));
        background.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 40, 10));

        salir1.setBackground(new java.awt.Color(255, 255, 255));

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setDoubleBuffered(true);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salir1Layout = new javax.swing.GroupLayout(salir1);
        salir1.setLayout(salir1Layout);
        salir1Layout.setHorizontalGroup(
            salir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        salir1Layout.setVerticalGroup(
            salir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/pregunta.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(19, 19, 19))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 540, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 580, 10));

        B.setBackground(java.awt.Color.gray);
        B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, 20));

        jLabel4.setText("3x3");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel5.setText("2x2");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Calculadora cramer 2x2 , 3x3 y 4x4");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 370, -1));
        background.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 250, 30));

        valor04.setForeground(java.awt.Color.gray);
        valor04.setText("0");
        valor04.setBorder(null);
        valor04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor04MousePressed(evt);
            }
        });
        background.add(valor04, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 40, 20));

        valor14.setForeground(java.awt.Color.gray);
        valor14.setText("0");
        valor14.setBorder(null);
        valor14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor14MousePressed(evt);
            }
        });
        background.add(valor14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 40, 20));

        valor24.setForeground(java.awt.Color.gray);
        valor24.setText("0");
        valor24.setBorder(null);
        valor24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor24MousePressed(evt);
            }
        });
        background.add(valor24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 40, 20));
        background.add(separador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 40, 10));
        background.add(separador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 40, 10));
        background.add(separador9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 40, 10));

        valor30.setForeground(java.awt.Color.gray);
        valor30.setText("0");
        valor30.setBorder(null);
        valor30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor30MousePressed(evt);
            }
        });
        background.add(valor30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 40, 20));

        valor31.setForeground(java.awt.Color.gray);
        valor31.setText("0");
        valor31.setBorder(null);
        valor31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor31MousePressed(evt);
            }
        });
        background.add(valor31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, 20));

        valor33.setForeground(java.awt.Color.gray);
        valor33.setText("0");
        valor33.setBorder(null);
        valor33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor33MousePressed(evt);
            }
        });
        background.add(valor33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 40, 20));

        valor32.setForeground(java.awt.Color.gray);
        valor32.setText("0");
        valor32.setBorder(null);
        valor32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor32MousePressed(evt);
            }
        });
        background.add(valor32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 40, 20));

        label8.setText("x3 +");
        background.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        label9.setText("x1 +");
        background.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        label10.setText("x2 +");
        background.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
        background.add(separador10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, 10));
        background.add(separador11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 40, 10));
        background.add(separador12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 40, 10));
        background.add(separador13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 40, 10));

        valor34.setForeground(java.awt.Color.gray);
        valor34.setText("0");
        valor34.setBorder(null);
        valor34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor34MousePressed(evt);
            }
        });
        background.add(valor34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 40, 20));
        background.add(separador14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 40, 10));

        label11.setText("x4 =");
        background.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        label12.setText("x4 =");
        background.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        label13.setText("x4 =");
        background.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        label14.setText("x4 =");
        background.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel7.setText("4x4");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 20));

        boton4.setBackground(java.awt.Color.blue);
        boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout boton4Layout = new javax.swing.GroupLayout(boton4);
        boton4.setLayout(boton4Layout);
        boton4Layout.setHorizontalGroup(
            boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        boton4Layout.setVerticalGroup(
            boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 20));

        MAX.setForeground(java.awt.Color.gray);
        MAX.setText("0");
        MAX.setBorder(null);
        MAX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MAXMousePressed(evt);
            }
        });
        background.add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 40, 20));

        label15.setText("Max");
        background.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));
        background.add(separador15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 40, 10));

        MIN.setForeground(java.awt.Color.gray);
        MIN.setText("0");
        MIN.setBorder(null);
        MIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MINMousePressed(evt);
            }
        });
        background.add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 40, 20));
        background.add(separador16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 40, 10));

        label16.setText("Min");
        background.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        llenar.setBackground(java.awt.Color.gray);
        llenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llenarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llenarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout llenarLayout = new javax.swing.GroupLayout(llenar);
        llenar.setLayout(llenarLayout);
        llenarLayout.setHorizontalGroup(
            llenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        llenarLayout.setVerticalGroup(
            llenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(llenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 20));

        jLabel8.setText("llenar");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel6.setText("calcular");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, 20));
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/uv logo.jpg"))); // NOI18N
        background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 80));

        respuestas.setEditable(false);
        respuestas.setBackground(new java.awt.Color(255, 255, 255));
        respuestas.setColumns(20);
        respuestas.setRows(5);
        respuestas.setTabSize(12);
        jScrollPane1.setViewportView(respuestas);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 350, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse );
    }//GEN-LAST:event_barraMouseDragged

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir1.setBackground(Color.red);
        salir.setForeground(Color.white);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir1.setBackground(Color.white);
        salir.setForeground(Color.black);
    }//GEN-LAST:event_salirMouseExited

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play();
        B.setBackground(Color.gray);
        boton4.setBackground(Color.gray);
        valor03.setVisible(false);
        valor13.setVisible(false);
        valor23.setVisible(false);
        valor22.setVisible(false);
        valor21.setVisible(false);
        valor20.setVisible(false);
        valor04.setVisible(false);
        valor14.setVisible(false);
        valor24.setVisible(false);
        valor34.setVisible(false);
        valor33.setVisible(false);
        valor32.setVisible(false);
        valor31.setVisible(false);
        valor30.setVisible(false);
        separador1.setVisible(false);
        separador2.setVisible(false);
        separador3.setVisible(false);
        separador4.setVisible(false);
        separador5.setVisible(false);
        separador6.setVisible(false);
        separador8.setVisible(false);
        separador9.setVisible(false);
        separador7.setVisible(false);
        separador14.setVisible(false);
        separador11.setVisible(false);
        separador12.setVisible(false);
        separador13.setVisible(false);
        separador10.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        label6.setVisible(false);
        label7.setVisible(false);
        label1.setText("+x2 =");
        label2.setText("+x2 =");
        label12.setVisible(false);
        label13.setVisible(false);
        label11.setVisible(false);
        label14.setVisible(false);
        label8.setVisible(false);
        label10.setVisible(false);
        label9.setVisible(false);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_AMouseClicked

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
        AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play();
        A.setBackground(Color.gray);
        boton4.setBackground(Color.gray);
        valor03.setVisible(true);
        valor13.setVisible(true);
        valor23.setVisible(true);
        valor22.setVisible(true);
        valor21.setVisible(true);
        valor20.setVisible(true);
        valor04.setVisible(false);
        valor14.setVisible(false);
        valor24.setVisible(false);
        valor34.setVisible(false);
        valor33.setVisible(false);
        valor32.setVisible(false);
        valor31.setVisible(false);
        valor30.setVisible(false);
        separador1.setVisible(true);
        separador2.setVisible(true);
        separador3.setVisible(true);
        separador4.setVisible(true);
        separador5.setVisible(true);
        separador6.setVisible(true);
        separador8.setVisible(false);
        separador9.setVisible(false);
        separador7.setVisible(false);
        separador14.setVisible(false);
        separador11.setVisible(false);
        separador12.setVisible(false);
        separador13.setVisible(false);
        separador10.setVisible(false);
        label3.setVisible(true);
        label4.setVisible(true);
        label5.setVisible(true);
        label6.setVisible(true);
        label7.setVisible(true);
        label1.setText("x2+");
        label2.setText("x2+");
        label4.setText("x3 =");
        label5.setText("x3 =");
        label6.setText("x3 =");
         label12.setVisible(false);
        label13.setVisible(false);
        label11.setVisible(false);
        label14.setVisible(false);
        label8.setVisible(false);
        label10.setVisible(false);
        label9.setVisible(false);
    }//GEN-LAST:event_BMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
             AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play(); 
            try{
               
                m1.RellenarMatriz(0, 0, valor00.getText());
            m1.RellenarMatriz(0, 1, valor01.getText());
            m1.RellenarMatriz(0, 2, valor02.getText());
            m1.RellenarMatriz(0, 3, valor03.getText());
            m1.RellenarMatriz(0, 4, valor04.getText());
            m1.RellenarMatriz(1, 0, valor10.getText());
            m1.RellenarMatriz(1, 1, valor11.getText());
            m1.RellenarMatriz(1, 2, valor12.getText());
            m1.RellenarMatriz(1, 3, valor13.getText());
            m1.RellenarMatriz(1, 4, valor14.getText());
            m1.RellenarMatriz(2, 0, valor20.getText());
            m1.RellenarMatriz(2, 1, valor21.getText());
            m1.RellenarMatriz(2, 2, valor22.getText());
            m1.RellenarMatriz(2, 3, valor23.getText());
            m1.RellenarMatriz(2, 4, valor24.getText());
            m1.RellenarMatriz(3, 0, valor30.getText());
            m1.RellenarMatriz(3, 1, valor31.getText());
            m1.RellenarMatriz(3, 2, valor32.getText());
            m1.RellenarMatriz(3, 3, valor33.getText());
            m1.RellenarMatriz(3, 4, valor34.getText());
                if(label9.isVisible()){
            if(m1.sePuedeResolver4x4()){
               respuestas.setForeground(Color.black);
                respuestas.setText("X1 = "+m1.resultados4x4()[0]+"\n"+"X2 = "+m1.resultados4x4()[1]+"\n"+"X3 = "+m1.resultados4x4()[2]+"\n"+"X4 = "+m1.resultados4x4()[3]
                        +"\n"+"==============================================="
              +"\n"+"Determinante de la matriz de identidad = "+m1.formaString(m1.determinantePrincipal4x4()));
               
            }else{
               respuestas.setForeground(Color.red);
                respuestas.setText("\n"+"\n"+"no tiene solución o tiene infinitas soluciones");           
            }
        }else if(label9.isVisible()==false&&label7.isVisible()){
             if(m1.SePuedeResolver3x3()){
                 respuestas.setForeground(Color.black);
                 respuestas.setText("X1 = "+m1.resultados3x3()[0]+"\n"+"X2 = "+m1.resultados3x3()[1]+"\n"+"X3 = "+m1.resultados3x3()[2]
              +"\n"+"==============================================="
                      +"\n"+"Determinante de la matriz de identidad = "+m1.formaString(m1.deltaS3x3()));
            }else{
                 respuestas.setForeground(Color.red);
                 respuestas.setText("\n"+"\n"+"no tiene solución o tiene infinitas soluciones");
             }
        }else{
            if(m1.SePuedeResolver2x2()){
                respuestas.setForeground(Color.black);
                respuestas.setText("\n"+"X1 = "+m1.X2x2()+"\n"+"X2 = "+m1.Y2x2()
                        +"\n"+"==============================================="
                        +"\n"+"determiannte de la matriz de identidad = "+m1.formaString(m1.deltaS2x2()));
            }else{
               respuestas.setForeground(Color.red);
                respuestas.setText("\n"+"\n"+"no tiene solución o tiene infinitas soluciones"); 
                
            }
             
        }
             
            }catch(Exception e){
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/Error.wav"));
            sonido.play(); 
             Error r1 = new Error();
             r1.setVisible(true);
             r1.setLocationRelativeTo(this);
             r1.cambiarTexto("Error: inserta solo numeros enteros o fracciones");
            }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(Color.red);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel1MouseExited

    private void AMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseEntered
        A.setBackground(Color.blue);
    }//GEN-LAST:event_AMouseEntered

    private void AMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseExited
        if(label7.isVisible()){
            A.setBackground(Color.gray);
        }
    }//GEN-LAST:event_AMouseExited

    private void BMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseEntered
        B.setBackground(Color.blue);
    }//GEN-LAST:event_BMouseEntered

    private void BMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseExited
        if(label9.isVisible()&&label7.isVisible()||label1.getText()=="+x2 ="){
            B.setBackground(Color.gray);
        }
    }//GEN-LAST:event_BMouseExited

    private void valor00MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor00MousePressed
        valor00.setText("");
        valor00.setForeground(Color.black);
    }//GEN-LAST:event_valor00MousePressed

    private void valor10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor10MousePressed
        valor10.setText("");
        valor10.setForeground(Color.black);
    }//GEN-LAST:event_valor10MousePressed

    private void valor20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor20MousePressed
        valor20.setText("");
        valor20.setForeground(Color.black);
    }//GEN-LAST:event_valor20MousePressed

    private void valor01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor01MousePressed
        valor01.setText("");
        valor01.setForeground(Color.black);
    }//GEN-LAST:event_valor01MousePressed

    private void valor11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor11MousePressed
        valor11.setText("");
        valor11.setForeground(Color.black);
    }//GEN-LAST:event_valor11MousePressed

    private void valor21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor21MousePressed
        valor21.setText("");
        valor21.setForeground(Color.black);
    }//GEN-LAST:event_valor21MousePressed

    private void valor02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor02MousePressed
       valor02.setText("");
       valor02.setForeground(Color.black);
    }//GEN-LAST:event_valor02MousePressed

    private void valor12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor12MousePressed
        valor12.setText("");
        valor12.setForeground(Color.black);
    }//GEN-LAST:event_valor12MousePressed

    private void valor22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor22MousePressed
        valor22.setText("");
        valor22.setForeground(Color.black);
    }//GEN-LAST:event_valor22MousePressed

    private void valor03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor03MousePressed
        valor03.setText("");
        valor03.setForeground(Color.black);
    }//GEN-LAST:event_valor03MousePressed

    private void valor13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor13MousePressed
        valor13.setText("");
        valor13.setForeground(Color.black);
    }//GEN-LAST:event_valor13MousePressed

    private void valor23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor23MousePressed
        valor23.setText("");
        valor23.setForeground(Color.black);
    }//GEN-LAST:event_valor23MousePressed

    private void valor04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor04MousePressed
        valor04.setText("");
        valor04.setForeground(Color.black);
    }//GEN-LAST:event_valor04MousePressed

    private void valor14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor14MousePressed
        valor14.setText("");
        valor14.setForeground(Color.black);
    }//GEN-LAST:event_valor14MousePressed

    private void valor24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor24MousePressed
        valor24.setText("");
        valor24.setForeground(Color.black);
    }//GEN-LAST:event_valor24MousePressed

    private void valor30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor30MousePressed
        valor30.setText("");
        valor30.setForeground(Color.black);
    }//GEN-LAST:event_valor30MousePressed

    private void valor31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor31MousePressed
        valor31.setText("");
        valor31.setForeground(Color.black);
    }//GEN-LAST:event_valor31MousePressed

    private void valor33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor33MousePressed
         valor33.setText("");
        valor33.setForeground(Color.black);
    }//GEN-LAST:event_valor33MousePressed

    private void valor34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor34MousePressed
        valor34.setText("");
        valor34.setForeground(Color.black);
    }//GEN-LAST:event_valor34MousePressed

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
         AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play();
        B.setBackground(Color.gray);
        A.setBackground(Color.gray);
        valor03.setVisible(true);
        valor13.setVisible(true);
        valor23.setVisible(true);
        valor22.setVisible(true);
        valor21.setVisible(true);
        valor20.setVisible(true);
        valor04.setVisible(true);
        valor14.setVisible(true);
        valor24.setVisible(true);
        valor34.setVisible(true);
        valor33.setVisible(true);
        valor32.setVisible(true);
        valor31.setVisible(true);
        valor30.setVisible(true);
        separador1.setVisible(true);
        separador2.setVisible(true);
        separador3.setVisible(true);
        separador4.setVisible(true);
        separador5.setVisible(true);
        separador6.setVisible(true);
        separador8.setVisible(true);
        separador9.setVisible(true);
        separador7.setVisible(true);
        separador14.setVisible(true);
        separador11.setVisible(true);
        separador12.setVisible(true);
        separador13.setVisible(true);
        separador10.setVisible(true);
        label3.setVisible(true);
        label4.setVisible(true);
        label5.setVisible(true);
        label6.setVisible(true);
        label7.setVisible(true);
        label1.setText("x2 +");
        label2.setText("x2 +");
        label12.setVisible(true);
        label13.setVisible(true);
        label11.setVisible(true);
        label14.setVisible(true);
        label8.setVisible(true);
        label10.setVisible(true);
        label9.setVisible(true);
    }//GEN-LAST:event_boton4MouseClicked

    private void boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseEntered
        boton4.setBackground(Color.blue);
    }//GEN-LAST:event_boton4MouseEntered

    private void boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseExited
        if(label9.isVisible()==false){
            boton4.setBackground(Color.gray);
        }
    }//GEN-LAST:event_boton4MouseExited

    private void llenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarMouseExited
      llenar.setBackground(Color.gray);
    }//GEN-LAST:event_llenarMouseExited

    private void llenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarMouseEntered
         llenar.setBackground(Color.red);
    }//GEN-LAST:event_llenarMouseEntered

    private void llenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarMouseClicked
        try{
        int max =Integer.valueOf(MAX.getText());
        int min =Integer.valueOf(MIN.getText());
        valor00.setText(m1.GenerarNumerosAleatorios(min, max));
        valor01.setText(m1.GenerarNumerosAleatorios(min, max));
        valor02.setText(m1.GenerarNumerosAleatorios(min, max));
        valor03.setText(m1.GenerarNumerosAleatorios(min, max));
        valor04.setText(m1.GenerarNumerosAleatorios(min, max));
        valor10.setText(m1.GenerarNumerosAleatorios(min, max));
        valor11.setText(m1.GenerarNumerosAleatorios(min, max));
        valor12.setText(m1.GenerarNumerosAleatorios(min, max));
        valor13.setText(m1.GenerarNumerosAleatorios(min, max));
        valor14.setText(m1.GenerarNumerosAleatorios(min, max));
        valor20.setText(m1.GenerarNumerosAleatorios(min, max));
        valor21.setText(m1.GenerarNumerosAleatorios(min, max));
        valor22.setText(m1.GenerarNumerosAleatorios(min, max));
        valor23.setText(m1.GenerarNumerosAleatorios(min, max));
        valor24.setText(m1.GenerarNumerosAleatorios(min, max));
        valor30.setText(m1.GenerarNumerosAleatorios(min, max));
        valor31.setText(m1.GenerarNumerosAleatorios(min, max));
        valor32.setText(m1.GenerarNumerosAleatorios(min, max));
        valor33.setText(m1.GenerarNumerosAleatorios(min, max));
        valor34.setText(m1.GenerarNumerosAleatorios(min, max));
        
        valor00.setForeground(Color.black);
        valor01.setForeground(Color.black);
        valor02.setForeground(Color.black);
        valor03.setForeground(Color.black);
        valor04.setForeground(Color.black);
        valor10.setForeground(Color.black);
        valor11.setForeground(Color.black);
        valor12.setForeground(Color.black);
        valor13.setForeground(Color.black);
        valor14.setForeground(Color.black);
        valor20.setForeground(Color.black);
        valor21.setForeground(Color.black);
        valor22.setForeground(Color.black);
        valor23.setForeground(Color.black);
        valor24.setForeground(Color.black);
        valor30.setForeground(Color.black);
        valor31.setForeground(Color.black);
        valor32.setForeground(Color.black);
        valor33.setForeground(Color.black);
        valor34.setForeground(Color.black);
         AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play();
        }catch(Exception e){
             AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/Error.wav"));
            sonido.play(); 
            Error r1 = new Error();
             r1.setVisible(true);
             r1.setLocationRelativeTo(this);
             r1.cambiarTexto("Error: inserta solo numeros enteros");
        }
        
        

    }//GEN-LAST:event_llenarMouseClicked

    private void MAXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAXMousePressed
        MAX.setText("");
        MAX.setForeground(Color.black);
    }//GEN-LAST:event_MAXMousePressed

    private void MINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMousePressed
        MIN.setText("");
        MIN.setForeground(Color.black);
    }//GEN-LAST:event_MINMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
      Tutorial t1 = new Tutorial();
      t1.setVisible(true);
       int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
      t1.setLocation(x1+30, y1-20);
       AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/newpackage/videoplayback.wav"));
            sonido.play();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void valor32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor32MousePressed
        valor32.setText("");
        valor32.setForeground(Color.black);
    }//GEN-LAST:event_valor32MousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JTextField MAX;
    private javax.swing.JTextField MIN;
    private javax.swing.JPanel background;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel boton4;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JPanel llenar;
    private javax.swing.JTextArea respuestas;
    private javax.swing.JLabel salir;
    private javax.swing.JPanel salir1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador10;
    private javax.swing.JSeparator separador11;
    private javax.swing.JSeparator separador12;
    private javax.swing.JSeparator separador13;
    private javax.swing.JSeparator separador14;
    private javax.swing.JSeparator separador15;
    private javax.swing.JSeparator separador16;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JSeparator separador7;
    private javax.swing.JSeparator separador8;
    private javax.swing.JSeparator separador9;
    private javax.swing.JTextField valor00;
    private javax.swing.JTextField valor01;
    private javax.swing.JTextField valor02;
    private javax.swing.JTextField valor03;
    private javax.swing.JTextField valor04;
    private javax.swing.JTextField valor10;
    private javax.swing.JTextField valor11;
    private javax.swing.JTextField valor12;
    private javax.swing.JTextField valor13;
    private javax.swing.JTextField valor14;
    private javax.swing.JTextField valor20;
    private javax.swing.JTextField valor21;
    private javax.swing.JTextField valor22;
    private javax.swing.JTextField valor23;
    private javax.swing.JTextField valor24;
    private javax.swing.JTextField valor30;
    private javax.swing.JTextField valor31;
    private javax.swing.JTextField valor32;
    private javax.swing.JTextField valor33;
    private javax.swing.JTextField valor34;
    // End of variables declaration//GEN-END:variables
}
